project_name: nais-cli
builds:
  - env: [ CGO_ENABLED=0 ]
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    id: nais
    dir: .
    main: ./main/nais_cli
    binary: nais
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: nais
    name: nais-cli
  header: |
    ## nais-cli ({{ .Version }})
brews:
  - tap:
      owner: nais
      name: homebrew-tap
      token: "{{ .Env.PUSH_TOKEN }}"
    name: nais
    homepage: "https://github.com/nais/nais-cli"
    description: "Simple Aiven Kafka Debug Cli"
    folder: Formula
    install: |
      bin.install "nais"
    test: |
      assert_match version, shell_output("#{bin}/nais version")
nfpms:
  - package_name: nais
    file_name_template: "{{ .PackageName }}_{{ .Version }}"
    vendor: NAV / nais team
    homepage: "https://github.com/nais/nais-cli"
    maintainer: NAV / nais team
    description: "Simple Aiven Kafka Debug Cli"
    license: MIT
    formats:
      - deb
    version_metadata: git
