project_name: nais-d
builds:
- env: [CGO_ENABLED=0, VERSION=v0.0.2]
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm64
  id: "nais-d"
  dir: .
  main: ./main/nais-d
  binary: nais-d
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: nais
    name: nais-d
brews:
- tap:
    owner: nais
    name: homebrew-tap
  name: nais-d
  homepage: "https://github.com/nais/nais-d"
  description: "Simple Aiven Kafka Debug Cli"
  folder: Formula
  install: |
    bin.install "nais-d"
  test: |
    assert_match version, shell_output("#{bin}/nais-d version")