name: Release master

on:
  repository_dispatch:
    types: [ elease-nais-d ]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test Go
        run: |
          go mod tidy -v
          go test

      - name: Set Git User
        uses: fregante/setup-git-user@v1

      - name: Set goreleaser tag
        run: |
          # echo "GORELEASER_CURRENT_TAG=${{ github.event.client_payload.current }}" >> $GITHUB_ENV
          # echo "GORELEASER_PREVIOUS_TAG=${{ github.event.client_payload.previous }}" >> $GITHUB_ENV

      - name: Checkout tag
        run: |
          git checkout tags/${{ github.event.client_payload.current }} -b refs/heads/master

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release -f .goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
